// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	httprpc "douyinProject/http/kitex_gen/httprpc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return userServiceServiceInfo
}

var userServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "UserService"
	handlerType := (*httprpc.UserService)(nil)
	methods := map[string]kitex.MethodInfo{
		"RegistMethod": kitex.NewMethodInfo(registMethodHandler, newUserServiceRegistMethodArgs, newUserServiceRegistMethodResult, false),
		"LoginMethod":  kitex.NewMethodInfo(loginMethodHandler, newUserServiceLoginMethodArgs, newUserServiceLoginMethodResult, false),
		"InfoMethod":   kitex.NewMethodInfo(infoMethodHandler, newUserServiceInfoMethodArgs, newUserServiceInfoMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "httprpc",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func registMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*httprpc.UserServiceRegistMethodArgs)
	realResult := result.(*httprpc.UserServiceRegistMethodResult)
	success, err := handler.(httprpc.UserService).RegistMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceRegistMethodArgs() interface{} {
	return httprpc.NewUserServiceRegistMethodArgs()
}

func newUserServiceRegistMethodResult() interface{} {
	return httprpc.NewUserServiceRegistMethodResult()
}

func loginMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*httprpc.UserServiceLoginMethodArgs)
	realResult := result.(*httprpc.UserServiceLoginMethodResult)
	success, err := handler.(httprpc.UserService).LoginMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceLoginMethodArgs() interface{} {
	return httprpc.NewUserServiceLoginMethodArgs()
}

func newUserServiceLoginMethodResult() interface{} {
	return httprpc.NewUserServiceLoginMethodResult()
}

func infoMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*httprpc.UserServiceInfoMethodArgs)
	realResult := result.(*httprpc.UserServiceInfoMethodResult)
	success, err := handler.(httprpc.UserService).InfoMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newUserServiceInfoMethodArgs() interface{} {
	return httprpc.NewUserServiceInfoMethodArgs()
}

func newUserServiceInfoMethodResult() interface{} {
	return httprpc.NewUserServiceInfoMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) RegistMethod(ctx context.Context, request *httprpc.RegistReq) (r *httprpc.RegistResp, err error) {
	var _args httprpc.UserServiceRegistMethodArgs
	_args.Request = request
	var _result httprpc.UserServiceRegistMethodResult
	if err = p.c.Call(ctx, "RegistMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) LoginMethod(ctx context.Context, request *httprpc.LoginReq) (r *httprpc.LoginResp, err error) {
	var _args httprpc.UserServiceLoginMethodArgs
	_args.Request = request
	var _result httprpc.UserServiceLoginMethodResult
	if err = p.c.Call(ctx, "LoginMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) InfoMethod(ctx context.Context, request *httprpc.InfoReq) (r *httprpc.InfoResp, err error) {
	var _args httprpc.UserServiceInfoMethodArgs
	_args.Request = request
	var _result httprpc.UserServiceInfoMethodResult
	if err = p.c.Call(ctx, "InfoMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
