// Code generated by Kitex v0.4.4. DO NOT EDIT.

package userservice

import (
	"context"
	user "douyinProject/relation/kitex_gen/user"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	FollowCountMethod(ctx context.Context, request *user.FollowCountReq, callOptions ...callopt.Option) (r *user.FollowCountResp, err error)
	FollowerCountMethod(ctx context.Context, request *user.FollowerCountReq, callOptions ...callopt.Option) (r *user.FollowerCountResp, err error)
	InfosMethod(ctx context.Context, request *user.InfosReq, callOptions ...callopt.Option) (r *user.InfosResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) FollowCountMethod(ctx context.Context, request *user.FollowCountReq, callOptions ...callopt.Option) (r *user.FollowCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowCountMethod(ctx, request)
}

func (p *kUserServiceClient) FollowerCountMethod(ctx context.Context, request *user.FollowerCountReq, callOptions ...callopt.Option) (r *user.FollowerCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.FollowerCountMethod(ctx, request)
}

func (p *kUserServiceClient) InfosMethod(ctx context.Context, request *user.InfosReq, callOptions ...callopt.Option) (r *user.InfosResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.InfosMethod(ctx, request)
}
