// Code generated by Kitex v0.4.4. DO NOT EDIT.

package chatservice

import (
	"context"
	httprpc "douyinProject/http/kitex_gen/httprpc"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return chatServiceServiceInfo
}

var chatServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "ChatService"
	handlerType := (*httprpc.ChatService)(nil)
	methods := map[string]kitex.MethodInfo{
		"ChatMethod":   kitex.NewMethodInfo(chatMethodHandler, newChatServiceChatMethodArgs, newChatServiceChatMethodResult, false),
		"ActionMethod": kitex.NewMethodInfo(actionMethodHandler, newChatServiceActionMethodArgs, newChatServiceActionMethodResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "httprpc",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func chatMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*httprpc.ChatServiceChatMethodArgs)
	realResult := result.(*httprpc.ChatServiceChatMethodResult)
	success, err := handler.(httprpc.ChatService).ChatMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceChatMethodArgs() interface{} {
	return httprpc.NewChatServiceChatMethodArgs()
}

func newChatServiceChatMethodResult() interface{} {
	return httprpc.NewChatServiceChatMethodResult()
}

func actionMethodHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*httprpc.ChatServiceActionMethodArgs)
	realResult := result.(*httprpc.ChatServiceActionMethodResult)
	success, err := handler.(httprpc.ChatService).ActionMethod(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newChatServiceActionMethodArgs() interface{} {
	return httprpc.NewChatServiceActionMethodArgs()
}

func newChatServiceActionMethodResult() interface{} {
	return httprpc.NewChatServiceActionMethodResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) ChatMethod(ctx context.Context, request *httprpc.ChatReq) (r *httprpc.ChatResp, err error) {
	var _args httprpc.ChatServiceChatMethodArgs
	_args.Request = request
	var _result httprpc.ChatServiceChatMethodResult
	if err = p.c.Call(ctx, "ChatMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ActionMethod(ctx context.Context, request *httprpc.ActionReq) (r *httprpc.ActionResp, err error) {
	var _args httprpc.ChatServiceActionMethodArgs
	_args.Request = request
	var _result httprpc.ChatServiceActionMethodResult
	if err = p.c.Call(ctx, "ActionMethod", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
