// Code generated by Kitex v0.4.4. DO NOT EDIT.

package chatservice

import (
	"context"
	httprpc "douyinProject/http/kitex_gen/httprpc"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ChatMethod(ctx context.Context, request *httprpc.ChatReq, callOptions ...callopt.Option) (r *httprpc.ChatResp, err error)
	ActionMethod(ctx context.Context, request *httprpc.ActionReq, callOptions ...callopt.Option) (r *httprpc.ActionResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatServiceClient struct {
	*kClient
}

func (p *kChatServiceClient) ChatMethod(ctx context.Context, request *httprpc.ChatReq, callOptions ...callopt.Option) (r *httprpc.ChatResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ChatMethod(ctx, request)
}

func (p *kChatServiceClient) ActionMethod(ctx context.Context, request *httprpc.ActionReq, callOptions ...callopt.Option) (r *httprpc.ActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ActionMethod(ctx, request)
}
